name: Deploy
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  gm-app-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./gm-app
          push: true
          cache-from: type=gha,scope=gm-app
          cache-to: type=gha,mode=max,scope=gm-app
          tags: ${{ env.DOCKER_IMAGE }}
  gm-app-run:
    needs: gm-app-deploy
    runs-on: ubuntu-latest
    env:
      NAME: gm-app
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MDTPBOX_URL }}
          username: ${{ secrets.MDTPBOX_USER }}
          key: ${{ secrets.MDTPBOX_SSH_KEY }}
          port: ${{ secrets.MDTPBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="gm.tokenpage.xyz"
            varsFile=~/.${NAME}.vars
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ${varsFile} \
                ${DOCKER_IMAGE}
  zm-app-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-zm-app:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./zm-app
          push: true
          cache-from: type=gha,scope=zm-app
          cache-to: type=gha,mode=max,scope=zm-app
          tags: ${{ env.DOCKER_IMAGE }}
  zm-app-run:
    needs: zm-app-deploy
    runs-on: ubuntu-latest
    env:
      NAME: zm-app
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-zm-app:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MDTPBOX_URL }}
          username: ${{ secrets.MDTPBOX_USER }}
          key: ${{ secrets.MDTPBOX_SSH_KEY }}
          port: ${{ secrets.MDTPBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="zm.tokenpage.xyz"
            varsFile=~/.${NAME}.vars
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ${varsFile} \
                ${DOCKER_IMAGE}
