name: Build
on:
  pull_request:
    branches: [main]
jobs:
  gm-app-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: gm-app
          load: true
          cache-from: type=gha,scope=gm-app
          cache-to: type=gha,mode=max,scope=gm-app
      - name: Build testable docker image
        uses: docker/build-push-action@v2
        with:
          context: gm-app
          load: true
          cache-from: type=gha,scope=gm-app
          cache-to: type=gha,mode=max,scope=gm-app
          tags: ${{ env.DOCKER_IMAGE }}
          target: build
      - name: Run linting
        run: |
          docker run --name lint $DOCKER_IMAGE npm run lint -- --output-file lint-results.json --output-file-format annotations
          docker cp lint:/gm-app/lint-results.json ./gm-app/lint-results.json
      - name: Upload linting results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./gm-app/lint-results.json
          check-name: lint-gm-app
          fail-on-error: false
          path-prefix: ./gm-app/
      - name: Run typing
        run: |
          docker run --name typing $DOCKER_IMAGE npm run type-check -- --output-file typing-results.json --output-file-format annotations
          docker cp typing:/app/typing-results.json ./gm-app/typing-results.json
      - name: Upload typing results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./gm-app/typing-results.json
          check-name: type-gm-app
          fail-on-error: false
          path-prefix: ./gm-app/
  zm-app-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: zm-app
          load: true
          cache-from: type=gha,scope=zm-app
          cache-to: type=gha,mode=max,scope=zm-app
      - name: Build testable docker image
        uses: docker/build-push-action@v2
        with:
          context: zm-app
          load: true
          cache-from: type=gha,scope=zm-app
          cache-to: type=gha,mode=max,scope=zm-app
          tags: ${{ env.DOCKER_IMAGE }}
          target: build
      - name: Run linting
        run: |
          docker run --name lint $DOCKER_IMAGE npm run lint -- --output-file lint-results.json --output-file-format annotations
          docker cp lint:/zm-app/lint-results.json ./zm-app/lint-results.json
      - name: Upload linting results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./zm-app/lint-results.json
          check-name: lint-zm-app
          fail-on-error: false
          path-prefix: ./zm-app/
      - name: Run typing
        run: |
          docker run --name typing $DOCKER_IMAGE npm run type-check -- --output-file typing-results.json --output-file-format annotations
          docker cp typing:/app/typing-results.json ./zm-app/typing-results.json
      - name: Upload typing results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./zm-app/typing-results.json
          check-name: type-zm-app
          fail-on-error: false
          path-prefix: ./zm-app/
